---
title: "Introduction and foundations"
description: |
  A brief introduction to the course, preview of things to come, and some foundational background material.
author:
  - name: Joshua Loftus
date: 01-15-2021
output:
  distill::distill_article:
    self_contained: false
preview: https://joshualoftus.com/ml4ds/01-introduction-foundations/slides/01-2-foundations_files/figure-html/gapminder-loess-1.png
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.retina = 3, warning = FALSE, message = FALSE)
library(tidyverse)
library(knitr)
library(gapminder)
theme_set(theme_minimal(base_size = 22))
```



```{r}
gm2007 <- gapminder %>% 
  filter(year == 2007) %>%
  mutate(gdp = log10(gdpPercap))
smoothing_model <- loess(lifeExp ~ gdp, data = gm2007, span = .4)
xrange <- range(gm2007$gdp)
xseq <- seq(from=xrange[1], to=xrange[2], length=80)

smooth_line <- predict(smoothing_model, newdata = data.frame(gdp = xseq), se=FALSE)
smooth_yhat <- predict(smoothing_model)
```




### Slides and notebooks

[Slides](slides/01-1-introduction.html) for first video

[Notebook](notebooks/gapminder.html) for `gapminder` example

[Notebook](notebooks/candy.html) for `candy` example

[Slides](slides/01-2-foundations.html) for last video

[Notebook](notebooks/seminar.html) from seminar
