---
title: "Machine learning"
subtitle: "Optimization"
author: "Joshua Loftus"
#institute: "LSE"
#date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["default", "xaringan-themer.css", "../../../theme.css"]
#    seal: false    
    lib_dir: libs
    nature:
      titleSlideClass: ["top", "left"]
      countdown: 59000
      highlightStyle: github
      highlightLines: true
      highlightSpans: true
      countIncrementalSlides: false
---

class: inverse

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(fig.retina = 3, warning = FALSE, message = FALSE)
options(knitr.table.format = "html")
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_duo_accent(
  primary_color = "#2d708e",
  secondary_color = "#230433",
  link_color = "#55c667",
  text_bold_color = '#f68f46',
  title_slide_text_color = "#292929",
  title_slide_background_color = "#ffffff", #"#042333",
  title_slide_background_image = "../../../files/theme/LSE/spiral_stairs.jpg",
#    "https://upload.wikimedia.org/wikipedia/commons/1/1a/Workhouse_Nantwich.jpg",
  title_slide_background_size = "cover",
  ) #or contain
```

```{r xaringanextra, include=FALSE, warning=FALSE}
library(xaringanExtra)
xaringanExtra::use_animate_all("slide_left")
xaringanExtra::use_tile_view()
xaringanExtra::use_panelset()
xaringanExtra::style_panelset_tabs(font_family = "inherit")
```

```{r tidyverse, include=FALSE, warning=FALSE}
library(tidyverse)
library(knitr)
theme_set(theme_minimal(base_size = 22))
set.seed(1)
library(broom)
library(modelr)
```

<style type="text/css">
.remark-slide-content {
    font-size: 1.2rem;
    padding: 1em 4em 1em 4em;
}
</style>

being biased is cool, actually

---

## Perfectly smooth data

Credit: Reddit user [SurfingPolice](https://www.reddit.com/r/dataisbeautiful/comments/lkjlhy/relationship_between_film_length_and_average_imdb/gnk46yh/)

```{r echo = FALSE, cache = TRUE}
titles <- read_tsv("~/Downloads/archive/title.basics.tsv")
ratings <- read_tsv("~/Downloads/archive/title.ratings.tsv")
df <- titles %>%
  filter(titleType  == "movie") %>%
  inner_join(ratings, by = "tconst") %>%
  mutate(runtimeMinutes = parse_number(runtimeMinutes, na = c("\\N")))
rm(titles)
rm(ratings)
```

```{r echo = FALSE}
df %>%
  drop_na(runtimeMinutes) %>%
  filter(runtimeMinutes < 60 * 6, runtimeMinutes > 30, numVotes > 10) %>%
  mutate(roundedRuntimeMinutes = floor(runtimeMinutes),
         decade = startYear - startYear %% 10) %>%
  group_by(roundedRuntimeMinutes) %>%
  summarise(
    avgRatingPerTime = mean(averageRating),
    n_movies = n()
  ) %>%
  ggplot(aes(roundedRuntimeMinutes, avgRatingPerTime, color = n_movies)) + 
  geom_point() +
  guides(color = FALSE) +
  labs(x = "Runtime", y = "Average Rating") +
  scale_x_continuous(breaks = seq(0, 360, 30)) + 
  theme(axis.title = element_text(face = "bold")) 
```

---

## Disaggregated

```{r echo = FALSE}
df %>%
  drop_na(runtimeMinutes) %>%
  filter(runtimeMinutes < 60 * 6, runtimeMinutes > 30, numVotes > 10) %>%
  mutate(roundedRuntimeMinutes = floor(runtimeMinutes),
         decade = startYear - startYear %% 10) %>%
  filter(!is.na(decade), decade > 1930) %>%
  ggplot(aes(runtimeMinutes, averageRating)) + 
  geom_point(alpha = 0.1) +
  guides(color = FALSE) +
  labs(x = "Runtime", y = "Average Rating") 
```